// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datamodel

var TableNames = struct {
	SchemaMigrations string
	UserCoin         string
	UserItem         string
	UserMonster      string
}{
	SchemaMigrations: "schema_migrations",
	UserCoin:         "user_coin",
	UserItem:         "user_item",
	UserMonster:      "user_monster",
}
